/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes.reader;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLOutput;
import java.util.ArrayList;
import java.util.NoSuchElementException;

public class App {
    public static void main(String[] args) {
        QuotesReader qr;
        String quote = null;
        try {
            //Make a new instance of the QuoteReader class
            qr = new QuotesReader("src/main/resources/quotescache.json");
        } catch (IOException e) {
            System.out.println("Quotes input file could not be written to.");
            e.printStackTrace();
            return;
        }

        // check if args are 0, if it is, will just run code to get a random quote
        if (args.length == 0) {
            quote = qr.getRandomQuotation().prettyPrint();
        } else if (args.length >= 2) {
            if (args[0].equals("author")) {
                quote = qr.getRandomQuotationByAuthor(args[1]).prettyPrint();
            } else if (args[0].equals("contains")) {
                quote = qr.getRandomQuotationByWord(args[1]).prettyPrint();
            } else if (args[0].equals("tag")) {
                quote = qr.getRandomQuotationByTag(args[1]).prettyPrint();
            }
        } else if (args[0].equals("help")) {
            System.out.println("Returns a random quote from our curated list of quotes.");
            System.out.println("Arguments: author [author-name]");
            System.out.println("Arguments: contains [word]");
            System.out.println("Arguments: tag [tag]");
            return;
        }

        if (quote == null) System.out.printf("%s is not a valid argument. Type help to see arguments.", args[0]);
        else {
            AnimalWriter aw = new AnimalWriter(System.out, 50);
            aw.fishSay(quote);
        }
    }
}